version: '2.1'

services:
  config:
    image: artsiom/config:0.1
    restart: always
    
                

  registry:
    image: artsiom/registry:0.1
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:8761


  student-service:
    image: artsiom/student-service:0.1
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 6001:6001


  school-service:
    image: artsiom/school-service:0.1
    restart: always
    depends_on:
      config:
        condition: service_healthy 
    ports:
      - 6002:6002
